package framework

import (
	"net"
	"airdispat.ch/common"
	"airdispat.ch/airdispatch"
	"code.google.com/p/goprotobuf/proto"
	"bytes"
	"errors"
)

// A structure that stores any errors generated by the Server framework
type ServerError struct {
	Location string
	Error error
}


// This interface defines the functions that an
// Airdispatch server must respond to in order to properly function
type ServerDelegate interface {
	HandleError(err *ServerError)
	LogMessage(toLog string)

	SavePublicMail(mailData []byte, fromAddress string)
	SavePrivateMail(mailData []byte, toAddresses []string) (messageId string)

	SaveIncomingAlert(alert *airdispatch.Alert, alertData []byte, fromAddr string)

	AllowSendConnection(fromAddr string) bool

	RetrieveMessageForUser(id string, addr string) (message []byte)
	RetrievePublic(fromAddr string, since uint64) (messages [][]byte)
	RetrieveInbox(addr string, since uint64) (messages [][]byte)
}

// The server structure tahat holds all of the necessary instance variables
type Server struct {
	LocationName string
	TrackerList []string
	Key *common.ADKey
	Delegate ServerDelegate
}

// Function that starts the server on a specific port
func (s *Server) StartServer(port string) (error) {
	// Resolve the Address of the Server
	service := ":" + port
	tcpAddr, _ := net.ResolveTCPAddr("tcp4", service)
	s.Delegate.LogMessage("Starting Server on " + service)

	// Start the Server
	listener, err := net.ListenTCP("tcp", tcpAddr)
	if err != nil {
		return err
	}
	s.Delegate.LogMessage("Server is Running...")

	s.serverLoop(listener)
	return nil
}

// Sends an error to the Server Delegate
func (s *Server) handleError(location string, error error) {
	s.Delegate.HandleError(&ServerError {
		Location: location,
		Error: error,
	})
}

// The loop that continues while waiting on clients to connect
func (s *Server) serverLoop(listener *net.TCPListener) {
	// Loop forever, waiting for connections
	for {
		// Accept a Connection
		conn, err := listener.Accept()
		if err != nil {
			s.handleError("Server Loop (Accepting New Client)", err)
			continue
		}

		// Concurrently handle the connection
		go s.handleClient(conn)
	}	
}

// Called when a client connects
func (s *Server) handleClient(conn net.Conn) {
	// Close the Connection after Handling
	defer conn.Close()

	// Read in the Message
	totalBytes, newMessage, err := common.ReadADMessagePrimative(conn)
	if err != nil {
		s.handleError("Handle Client (Reading Signed Message)", err)
		return
	}

	// Switch based on the Message Type
	switch newMessage.MessageType {

		case common.ALERT_MESSAGE:
			// Unmarshal the stored message
			assigned := &airdispatch.Alert{}
			err := proto.Unmarshal(newMessage.Payload, assigned)
			if err != nil {
				s.handleError("Handle Client (Unloading Alert Payload)", err)
				return
			}

			// Handle the Alert
			s.handleAlert(assigned, totalBytes, newMessage.FromAddress)

		case common.RETRIEVAL_MESSAGE:
			// Unmarshal the stored message
			assigned := &airdispatch.RetrieveData{}
			err := proto.Unmarshal(newMessage.Payload, assigned)
			if err != nil {
				s.handleError("Handle Client (Unloading Retrieval Payload)", err)
				return
			}

			// Handle the Retrieval Message
			s.handleRetrieval(assigned, newMessage.FromAddress, conn)

		case common.SEND_REQUEST:

			if !s.Delegate.AllowSendConnection(newMessage.FromAddress) {
				return
			}

			// Unmarshal the stored message
			assigned := &airdispatch.SendMailRequest{}
			err := proto.Unmarshal(newMessage.Payload, assigned)
			if err != nil {
				s.handleError("Handle Client (Unloading Send Request Payload)", err)
				return
			}

			// Handle the Send Request
			s.handleSendRequest(assigned, newMessage.FromAddress)
	}
}

// Function that Handles an Alert of a Message
func (s *Server) handleAlert(alert *airdispatch.Alert, alertData []byte, fromAddr string) {
	s.Delegate.SaveIncomingAlert(alert, alertData, fromAddr)
}

// Function that Handles a DataRetrieval Message
func (s *Server) handleRetrieval(retrieval *airdispatch.RetrieveData, toAddr string, conn net.Conn) {
	// Get the Type of the Message and Switch on it
	c := retrieval.RetrievalType
	switch {
		// Receieved a Normal Retrieval Message (Lookup the Message ID)
		case bytes.Equal(c, common.ADRetrievalNormal):
			message := s.Delegate.RetrieveMessageForUser(*retrieval.MessageId, toAddr)

			if message == nil {
				// If there is no message stored with that ID, then send back an error
				conn.Write(s.Key.CreateErrorMessage("400", "no message for that id and user"))
				return
			}

			// If it passes these checks, send the message back through the connection
			conn.Write(common.AddPrefixToData(message))

		// Received a Public Retrieval Message (Return all Messages Since the Date Provided)
		case bytes.Equal(c, common.ADRetrievalPublic):

			output := s.Delegate.RetrievePublic(*retrieval.FromAddress, *retrieval.SinceDate)

			if len(output) == 0 {
				conn.Write(s.Key.CreateErrorMessage("400", "No public messages for that address"))
				return
			}

			// Alert the Client that an Array is Coming
			arrayData, err := s.Key.CreateArrayedMessage(uint32(len(output)))
			if err != nil {
				s.handleError("Handle Retrieval (Creating AD Message)", err)
				return
			}

			conn.Write(arrayData)

			// Write all of the Data
			for _, v := range(output) {
				conn.Write(common.AddPrefixToData(v))
			}

		// Received a Mine Retrieval Message (Return all Messages that are Stored - Since the Date Provided)	
		case bytes.Equal(c, common.ADRetrievalMine):
			output := s.Delegate.RetrieveInbox(toAddr, *retrieval.SinceDate)

			if len(output) == 0 {
				conn.Write(s.Key.CreateErrorMessage("400", "no inbox messages for that address"))
				return
			}

			arrayData, err := s.Key.CreateArrayedMessage(uint32(len(output)))
			if err != nil {
				s.handleError("Handle Retrieval (Creating AD Message)", err)
				return
			}

			conn.Write(arrayData)

			// Write all of the Data
			for _, v := range(output) {
				conn.Write(common.AddPrefixToData(v))
			}

		default:
			s.handleError("Handle Retrieval", errors.New("Invalid Retrieval Type"))
	}
}

// Function that Handles a Request to Send a Message
func (s *Server) handleSendRequest(request *airdispatch.SendMailRequest, fromAddr string) {
	// Check to see if it a public message or not
	if len(request.ToAddress) != 0 && request.ToAddress[0] != fromAddr && request.ToAddress[0] != "" {
		hash := s.Delegate.SavePrivateMail(request.StoredMessage, request.ToAddress)

		for _, v := range(request.ToAddress) {
			// For every address that the Message is to be sent to, lookup its location and send it an alert
			loc, _, err := common.LookupLocation(v, s.TrackerList, s.Key)
			if err != nil {
				s.handleError("Handle Send Request (Lookup Address)", errors.New("Address Lookup Failed"))
				return
			}

			s.SendAlert(loc, hash, v)
		}

	} else {
		s.Delegate.SavePublicMail(request.StoredMessage, fromAddr)
	}
}

// A function that delivers an alert to a location
func (s *Server) SendAlert(location string, message_id string, toAddr string) {
	conn, err := common.ConnectToServer(location)
	if err != nil {
		s.handleError("Send Alert", errors.New("Unable to Connect to Server"))
		return
	}

	// Populate the Alert message
	newAlert := &airdispatch.Alert {
		ToAddress: &toAddr,
		Location: &s.LocationName,
		MessageId: &message_id,
	}
	alertData, _ := proto.Marshal(newAlert)

	// Create the Message to Send
	newMessage := &common.ADMessagePrimative{alertData, common.ALERT_MESSAGE, ""}

	bytesToSend, err := s.Key.CreateADMessagePrimative(newMessage)
	if err != nil {
		s.handleError("Send Alert (Create AD Message)", err)
		return
	}

	// Write the Message
	conn.Write(bytesToSend)
	conn.Close()
}
