// Code generated by protoc-gen-go.
// source: Message.proto
// DO NOT EDIT!

package airdispatch

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SendMailRequest struct {
	ToAddress        []string `protobuf:"bytes,1,rep,name=to_address" json:"to_address,omitempty"`
	StoredMessage    *Mail    `protobuf:"bytes,2,req,name=stored_message" json:"stored_message,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SendMailRequest) Reset()         { *m = SendMailRequest{} }
func (m *SendMailRequest) String() string { return proto.CompactTextString(m) }
func (*SendMailRequest) ProtoMessage()    {}

func (m *SendMailRequest) GetToAddress() []string {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *SendMailRequest) GetStoredMessage() *Mail {
	if m != nil {
		return m.StoredMessage
	}
	return nil
}

type Mail struct {
	FromAddress      *string `protobuf:"bytes,1,req,name=from_address" json:"from_address,omitempty"`
	Encryption       *string `protobuf:"bytes,2,req,name=encryption" json:"encryption,omitempty"`
	Data             []byte  `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Mail) Reset()         { *m = Mail{} }
func (m *Mail) String() string { return proto.CompactTextString(m) }
func (*Mail) ProtoMessage()    {}

func (m *Mail) GetFromAddress() string {
	if m != nil && m.FromAddress != nil {
		return *m.FromAddress
	}
	return ""
}

func (m *Mail) GetEncryption() string {
	if m != nil && m.Encryption != nil {
		return *m.Encryption
	}
	return ""
}

func (m *Mail) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MailData struct {
	Payload          []*MailData_DataType `protobuf:"bytes,1,rep,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *MailData) Reset()         { *m = MailData{} }
func (m *MailData) String() string { return proto.CompactTextString(m) }
func (*MailData) ProtoMessage()    {}

func (m *MailData) GetPayload() []*MailData_DataType {
	if m != nil {
		return m.Payload
	}
	return nil
}

type MailData_DataType struct {
	TypeName         *string `protobuf:"bytes,1,req,name=type_name" json:"type_name,omitempty"`
	Payload          []byte  `protobuf:"bytes,2,req,name=payload" json:"payload,omitempty"`
	Encryption       *string `protobuf:"bytes,3,opt,name=encryption" json:"encryption,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MailData_DataType) Reset()         { *m = MailData_DataType{} }
func (m *MailData_DataType) String() string { return proto.CompactTextString(m) }
func (*MailData_DataType) ProtoMessage()    {}

func (m *MailData_DataType) GetTypeName() string {
	if m != nil && m.TypeName != nil {
		return *m.TypeName
	}
	return ""
}

func (m *MailData_DataType) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MailData_DataType) GetEncryption() string {
	if m != nil && m.Encryption != nil {
		return *m.Encryption
	}
	return ""
}

type SignedMessage struct {
	Payload           []byte     `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	SigningKey        []byte     `protobuf:"bytes,2,opt,name=signing_key" json:"signing_key,omitempty"`
	Signature         *Signature `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	MessageType       *string    `protobuf:"bytes,4,opt,name=message_type" json:"message_type,omitempty"`
	SignatureFunction *string    `protobuf:"bytes,5,opt,name=signature_function" json:"signature_function,omitempty"`
	XXX_unrecognized  []byte     `json:"-"`
}

func (m *SignedMessage) Reset()         { *m = SignedMessage{} }
func (m *SignedMessage) String() string { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()    {}

func (m *SignedMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SignedMessage) GetSigningKey() []byte {
	if m != nil {
		return m.SigningKey
	}
	return nil
}

func (m *SignedMessage) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedMessage) GetMessageType() string {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return ""
}

func (m *SignedMessage) GetSignatureFunction() string {
	if m != nil && m.SignatureFunction != nil {
		return *m.SignatureFunction
	}
	return ""
}

type Signature struct {
	R                []byte `protobuf:"bytes,1,req,name=r" json:"r,omitempty"`
	S                []byte `protobuf:"bytes,2,req,name=s" json:"s,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}

func (m *Signature) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Signature) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

type Alert struct {
	ToAddress        *string `protobuf:"bytes,1,opt,name=to_address" json:"to_address,omitempty"`
	Location         *string `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	MessageId        *string `protobuf:"bytes,3,opt,name=message_id" json:"message_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}

func (m *Alert) GetToAddress() string {
	if m != nil && m.ToAddress != nil {
		return *m.ToAddress
	}
	return ""
}

func (m *Alert) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *Alert) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

type RetrieveData struct {
	MessageId        *string `protobuf:"bytes,1,opt,name=message_id" json:"message_id,omitempty"`
	ToAddress        *string `protobuf:"bytes,2,opt,name=to_address" json:"to_address,omitempty"`
	FilterOptions    *string `protobuf:"bytes,3,opt,name=filter_options" json:"filter_options,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RetrieveData) Reset()         { *m = RetrieveData{} }
func (m *RetrieveData) String() string { return proto.CompactTextString(m) }
func (*RetrieveData) ProtoMessage()    {}

func (m *RetrieveData) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *RetrieveData) GetToAddress() string {
	if m != nil && m.ToAddress != nil {
		return *m.ToAddress
	}
	return ""
}

func (m *RetrieveData) GetFilterOptions() string {
	if m != nil && m.FilterOptions != nil {
		return *m.FilterOptions
	}
	return ""
}

type AddressRegistration struct {
	Address          *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	PublicKey        []byte  `protobuf:"bytes,2,req,name=public_key" json:"public_key,omitempty"`
	Location         *string `protobuf:"bytes,3,req,name=location" json:"location,omitempty"`
	Username         *string `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddressRegistration) Reset()         { *m = AddressRegistration{} }
func (m *AddressRegistration) String() string { return proto.CompactTextString(m) }
func (*AddressRegistration) ProtoMessage()    {}

func (m *AddressRegistration) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *AddressRegistration) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *AddressRegistration) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *AddressRegistration) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type AddressRequest struct {
	Address          *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	NeedKey          *bool   `protobuf:"varint,2,opt,name=need_key" json:"need_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddressRequest) Reset()         { *m = AddressRequest{} }
func (m *AddressRequest) String() string { return proto.CompactTextString(m) }
func (*AddressRequest) ProtoMessage()    {}

func (m *AddressRequest) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *AddressRequest) GetNeedKey() bool {
	if m != nil && m.NeedKey != nil {
		return *m.NeedKey
	}
	return false
}

type AddressResponse struct {
	ServerLocation   *string `protobuf:"bytes,1,req,name=server_location" json:"server_location,omitempty"`
	PublicKey        []byte  `protobuf:"bytes,2,opt,name=public_key" json:"public_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddressResponse) Reset()         { *m = AddressResponse{} }
func (m *AddressResponse) String() string { return proto.CompactTextString(m) }
func (*AddressResponse) ProtoMessage()    {}

func (m *AddressResponse) GetServerLocation() string {
	if m != nil && m.ServerLocation != nil {
		return *m.ServerLocation
	}
	return ""
}

func (m *AddressResponse) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
}
